# Generated by Django 4.0.4 on 2022-05-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='created_by',
            new_name='created_by_usr',
        ),
    ]
